### PR TITLE
expose completion.hint

### PR DESCRIPTION
**Pull request by kasperpeulen**
attempts to fix this issue: https://github.com/google/codemirror.dart/issues/28

This can be used in the following way:
```dart
HintResults _dartCompleter(CodeMirror editor, [HintsOptions options]) {
  Position cur = editor.getCursor();
  String word = _getCurrentWord(editor).toLowerCase();
  void hintFunction(CodeMirror cm, HintResult self, Map data) {
    self.defaultHint(cm,self,data);
    cm.getDoc().setCursor(new Position(cm.getDoc().getCursor().line, cm.getDoc().getCursor().ch-1));
  }
  List<HintResult> list = [
    new HintResult("print()", hint: hintFunction),
    new HintResult("print2()", hint: hintFunction)
  ];

  return new HintResults.fromHints(
      list,
      new Position(cur.line, cur.ch - word.length),
      new Position(cur.line, cur.ch));
}
```

To get this result:

### CODE REVIEW

**Comment by devoncarew** [comment]
Looks like we had the same idea: https://github.com/google/codemirror.dart/pull/30 :)

**Comment by kasperpeulen** [comment]
@devoncarew  Haha, probably yours is better :P But at least I learned a lot about jsinterop during my struggles creating this :)

**Comment by kasperpeulen** [comment]
Okay, two the same pull request makes no sense :) closing this

**Comment by devoncarew** [comment]
Thanks anyway - it was an unfortunate bit of overlap.

**Pull request closed without merging**
