### PR TITLE
removed dart:async

### PR DESCRIPTION
**Pull request by Himanshuranjan30**
removed unused dart:async

### CODE REVIEW

**Comment by devoncarew** [comment]
From https://travis-ci.org/github/google/codemirror.dart/builds/729380180#L338, we'll likely need to update the sdk constraint in the pubspec to >= dart 2.1.

**Comment by Himanshuranjan30** [comment]
Should I do that @devoncarew ?

**Comment by devoncarew** [comment]
Thanks! This looks good now. (we generally don't want to merge a PR if the CI system breaks with it)

**Review by devoncarew — APPROVED** [review]

**Comment by Himanshuranjan30** [comment]
Thanks! feels great to be a contributor.

**Pull request merged**
