### PR TITLE
Feat[addons] Add SearchCursor wrapper

### PR DESCRIPTION
**Pull request by ayshiff**
This PR adds a wrapper around the `addon/search/searchcursor.js` addon.
This wrapper will be used for https://github.com/dart-lang/dart-pad/issues/1866

### CODE REVIEW

**Review by domesticmouse — COMMENTED** [review]
Is there any way to add testing for this code?

**Comment by ayshiff** [comment]
> Is there any way to add testing for this code?

I will add some tests for this addon 👍

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
Thank you @ayshiff!

**Pull request merged**
