### PR TITLE
Updated to CodeMirror 5.41.0 and exposed more themes.

### PR DESCRIPTION
**Pull request by domesticmouse**
Hey @devoncarew,

I'm curious what the process is for updating the CodeMirror.dart project is. I've up'd the CodeMirror version and run the sample code against the updated CodeMirror.dart package. It looks like it still works as intended.

I have yet to dig through all of the deltas in the change notes to expose new functionality, but I figure the bug fixes would be a worthwhile gain, justifying a release.

Thoughts?

### CODE REVIEW

**Comment by devoncarew** [comment]
Hi, and thanks! The process is described here: https://github.com/google/codemirror.dart/blob/master/updating_codemirror.md. We very much do want a rev. to a new codemirror. Let me look through this PR now (we may want to redo the PR based on the update process, to make sure there are minimal diffs with earlier versions of the package).

**Comment by devoncarew** [comment]
Changes look good! I'll merge them. Can you follow up with a PR adding yourself to the authors file (https://github.com/google/codemirror.dart/blob/master/AUTHORS)? Thanks!

**Comment by devoncarew** [comment]
Actually, scratch that re: adding yourself to the AUTHORS file - you're covered by the Google, Inc. line.

**Comment by domesticmouse** [comment]
Thanks Devon 😎

**Pull request merged**
