### PR TITLE
CodeMirror.dart 0.7.0 release

### PR DESCRIPTION
**Pull request by domesticmouse**
TBR @parlough

### CODE REVIEW

**Comment by parlough** [comment]
I was just thinking about this while eating actually, sorry that I didn't catch it in the earlier review.

**Comment by peter100u** [comment]
May I ask, does codemirror.dart have a plan to support mobile terminals, I need to use it urgently in my mobile project

**Comment by parlough** [comment]
@peter100u Do you mean in a Flutter application? codemirror.dart is based on the DOM and web technologies, so won't work directly in a Flutter app.

**Comment by peter100u** [comment]
> @peter100u Do you mean in a Flutter application? codemirror.dart is based on the DOM and web technologies, so won't work directly in a Flutter app.

Yes, but there are currently some iframes or html to widget solutions in the relevant flutter web projects to implement the previous web projects, and codemirror6 has better support for mobile terminals, and I look forward to you trying more

**Pull request merged**
