### PR TITLE
CodeMirror v5.48.2

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by domesticmouse** [comment]
I didn't see any changes in the JS that would require changes in the Dart API. What did I miss?

**Comment by devoncarew** [comment]
I meant this change isn't bringing in any changes to the Dart mode in codemirror (the dart syntax highlighting). From recent discussion on the dartpad lists, I'd thought that changes to the mode were likely or being considered.

But it sounds like this is just a straight rev. of the codemirror resources.

**Comment by domesticmouse** [comment]
Adding in @johnpryan to comment on status of dart mode changes...

**Comment by johnpryan** [comment]
the dart changes still haven't been released, unfortunately: [https://github.com/codemirror/CodeMirror/compare/5.48.2...master](https://github.com/codemirror/CodeMirror/compare/5.48.2...master)

**Pull request merged**
