### PR TITLE
expose pick and update events for completion

### PR DESCRIPTION
**Pull request by kasperpeulen**

### CODE REVIEW

**Comment by devoncarew** [comment]
Have you tried running `example/simple.html` with this change? These docs:
```
"select" (completion, Element)
Fired when a completion is selected. Passed the completion value (string or object) and the DOM node that represents it in the menu.
"pick" (completion)
Fired when a completion is picked. Passed the completion value (string or object).
```
Seem in indicate that we'll need more args for `pick` and `select`. Also, I think the completion will come in as either a String or a JsObject. If it's a JsObject, we may want to convert it into a Dart Map, and then doc that we'll pass a String or a Map.

I'm happy to look at this myself later -

**Comment by kasperpeulen** [comment]
Yeah, I added an arg to pick, but I didn't expose it as I was not sure how
to convert completion (as jsObject) to a dart object.

I didn't know about the select thing, will add that as well.

2015-04-08 22:54 GMT+02:00 Devon Carew <notifications@github.com>:

> Have you tried running example/simple.html with this change? These docs:
>
> "select" (completion, Element)
> Fired when a completion is selected. Passed the completion value (string or object) and the DOM node that represents it in the menu.
> "pick" (completion)
> Fired when a completion is picked. Passed the completion value (string or object).
>
> Seem in indicate that we'll need more args for pick and select. Also, I
> think the completion will come in as either a String or a JsObject. If it's
> a JsObject, we may want to convert it into a Dart Map, and then doc that
> we'll pass a String or a Map.
>
> I'm happy to look at this myself later -
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/codemirror.dart/pull/37#issuecomment-91034269>.
>



-- 
Kasper

**Comment by devoncarew** [comment]
lgtm

**Comment by devoncarew** [comment]
This has been pushed to pub as `0.2.5`.

**Pull request merged**
