### PR TITLE
removed unused dart:async import as dart:core already have those features.

### PR DESCRIPTION
**Pull request by Himanshuranjan30**

### CODE REVIEW

**Comment by devoncarew** [comment]
Thanks for the PR! `dart:async` is no longer required if you're just using `Future` (that's also available from `dart:core`) now. You still need the import for other types (`Stream`, ...).

**Comment by Himanshuranjan30** [comment]
Yes,future and stream are available in dart:core.

**Comment by devoncarew** [comment]
Ah, yes, `Stream` is in core. If you check the CI, we have a use of StreamController - that'll still need the import (https://travis-ci.org/github/google/codemirror.dart/builds/729254174#L310).

**Comment by Himanshuranjan30** [comment]
Yes it's in js utils.dart. I can create another PR for codemirror.dart right? @devoncarew

**Comment by devoncarew** [comment]
You should be able to update this one for the fixes. You'll also need to sign the google CLA before this can be merged - there are some instructions from the comment by the CL bot.

Thanks for the contribution!

**Comment by Himanshuranjan30** [comment]
Sure,Close his issue now.I will raise a new one and send a PR accordingly @devoncarew

**Comment by devoncarew** [comment]
Closing in favor of https://github.com/google/codemirror.dart/pull/124.

**Pull request closed without merging**
