### PR TITLE
Migrate dart:html to package:web

### PR DESCRIPTION
**Pull request by erwamartin**
This PR migrates `dart:html` to  `package:web` (https://dart.dev/interop/js-interop/package-web).

### CODE REVIEW

**Comment by erwamartin** [comment]
I signed the CLA ✅

**Comment by domesticmouse** [comment]
PTAL @johnpryan

**Comment by domesticmouse** [comment]
I'm going to go ahead and land this, I think @johnpryan is a tad busy at the moment.

**Comment by johnpryan** [comment]
Sorry, I didn't have a chance to look at this. @erwamartin have you validate that this code works correctly? Migrating to `package:web` is only half the battle for Wasm compatibility, you need to also migrate from `dart:js` to `dart:js_interop`. See the [JS interop](https://dart.dev/interop/js-interop) for details.

**Comment by erwamartin** [comment]
Yes, I tested it and I'm using it in my project.
However, you are right, I forgot to migrate `dart:js` in this package as well.
I can open another PR later this week to take care of the required changes.

**Pull request merged**
