### PR TITLE
Removes redundant "new" usage while calling constructors.

### PR DESCRIPTION
**Pull request by rkinabhi**
- Reduce verbosity of code by removing redundant "new" while calling constructors.
- format code.

### CODE REVIEW

**Comment by domesticmouse** [comment]
Seeing as though you have done the hard work, do you want to add [unnecessary_new](http://dart-lang.github.io/linter/lints/unnecessary_new.html) to [analysis_options.yaml](https://github.com/google/codemirror.dart/blob/master/analysis_options.yaml)?

**Comment by devoncarew** [comment]
If @domesticmouse has verified that this is just a syntactic change (which it looks like it is), lgtm.

Can you add yourself to the https://github.com/google/codemirror.dart/blob/master/AUTHORS file as part of this PR? Thanks!

**Comment by domesticmouse** [comment]
I'm happy with this PR, I can merge once the AUTHORS file is updated. Thanks!

**Comment by rkinabhi** [comment]
@devoncarew I have added my dets to _AUTHORS_.
@domesticmouse I have updated the _analysis_options.yaml_ with the _unnecessary_new_ rule and have made required changes in test and tool directories. 👍

**Comment by domesticmouse** [comment]
Thanks for the PR!

**Pull request merged**
